# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
#  - name: Home
#    url: /
#    weight: 10
  - name: SPARQL
    url: http://ddbkg.fiz-karlsruhe.de
    weight: 10
  - name: GitHub
    url: https://github.com/ISE-FIZKarlsruhe/ddbkg
    weight: 20
  - name: Publications
    url: publication/
    weight: 20
  - name: Documentation
    url: docs/
    weight: 30
